### ISSUE TITLE
Mount/Umount Volumes 

### ISSUE THREAD

**Issue by dianlight** [dianlight/srat#2]
- [x] Mount and Umount Volume
- [x] Manage duplicate label for mountpoint
- [x] Mount options UI
- [x] Share / Unshare Volume
- [x] Mount status and config persistence
- [x] CLI to mount and umount
