### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by dianlight** [dianlight/srat#8]
- [ ] Tabs and navigation on mobile
- [ ] NavBar on mobile
- [ ] Update circolar progress
- [ ] Password/Secret field

**Comment by dianlight** [comment]
- [ ] UI Refactor to manage Folder mount as bind disk
